---
version: 2
project_name: ovh-dyndns
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    binary: "{{ tolower .ProjectName }}"
checksum:
  name_template: "Checksums.txt"
archives:
  - name_template: >-
      {{ tolower .ProjectName }}-{{ tolower .Version }}.
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}
      {{- end }}.
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ tolower .Arch }}
      {{- end }}
    files:
      - config/config.conf
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - maintainer: AndyZ <info@andycraftz.eu>
    description: DynDNS Client for OVH
    homepage: https://github.com/4ndyZ/OVH-DynDNS
    file_name_template: >-
      {{ tolower .ProjectName }}_{{ tolower .Version }}+{{ .Os }}_{{ tolower .Arch }}
    license: GPL-3.0
    # Build as deb for Debian based distributions and rpm for RedHat based distributions
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: web
    contents:
      # Config file
      - src: config/config.conf
        dst: /etc/ovh-dyndns/config.conf
        type: "config|noreplace"
        file_info:
          mode: 0640
          owner: root
          group: ovh-dyndns
      # Systemd service file
      - src: service/service.service
        dst: /usr/lib/systemd/system/ovh-dyndns.service
    # Install and remove scripts
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      postremove: "scripts/postremove.sh"
    overrides:
      rpm:
        file_name_template: >-
          {{ tolower .ProjectName }}-{{ tolower .Version }}-1.{{ .Os }}.
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else if eq .Arch "arm" }}armhfp
          {{- else }}{{ tolower .Arch }}
          {{- end }}
